Update/partial rewrite of editable-grid
wicketstuff/core pull request #756
Opened 2023-10-26 16:42 UTC by silasporth

While working on a project, I came across the editable-grid and wanted to use it. But I found some bugs that I couldn't fix unless I ported the whole structure to my project. Well, I did that because I liked the idea of the base so much and then I decided to fix the bugs here as well.

What I did:
- Added many Javadoc comments for a better understanding of the project
- Changed the visibility of most the methods for an increased extensibility
- Renamed a lot of files and methods to be more appropriate
- Updated the EditableDataTable to the newest version of Wicket Extensions' DataTable
- Fixed the sortability of EditableListDataProviders
- Redesigned the Add Feature with AddRowToolbar
- Refactored the editable columns
- Fixed the form validation done by EditableTableSubmitLink
- Ajax ready Toolbars
- Expanded the accessibilty of EditableGrid

If there are problems with any of these changes, I'm happy to help.

2023-10-26 19:44 UTC, martin-g approved these changes
LGTM!

The API breaks may make someone unhappy though! An upgrade from 9.x to 10.x will be painful!

2023-10-26 19:44 UTC, martin-g commented on editable-grid-parent/editable-grid-examples/pom.xml
> +			<version>${slf4j.version}</version>
Isn't that for testing too ?

2023-10-27 02:58 UTC, solomax requested changes
LGTM :)

with minor changes :)

2023-10-27 02:58 UTC, solomax commented on editable-grid-parent/editable-grid-examples/pom.xml
> +			<version>5.9.3</version>
please remove versions from here (they are defined in `dependencyManagement` at parent pom

2023-10-27 02:58 UTC, solomax commented on editable-grid-parent/editable-grid-examples/src/main/java/org/wicketstuff/egrid/page/HomePage.html
> +<div style="display: flex; justify-content: center;">
please avoid using of inline styles

2023-10-27 05:54 UTC, silasporth commented on editable-grid-parent/editable-grid-examples/pom.xml
> +			<version>${slf4j.version}</version>
Yes

2023-10-27 05:58 UTC, solomax approved these changes

2023-10-27 06:42 UTC, merged

2023-10-27 06:42 UTC, solomax commented
Thanks for the contribution @silasporth !

2024-03-19 14:34 UTC, ilgrosso commented
Hi @silasporth I am trying to understand how to update my code from 10.0.0-M1 to 10.0.0 (see #849) but having some issues: is there any usage sample around?

2024-03-20 08:13 UTC, silasporth commented
> Hi @silasporth I am trying to understand how to update my code from 10.0.0-M1 to 10.0.0 (see #849) but having some issues: is there any usage sample around?

Hi, currently there is only the example in editable-grid-parent/editable-grid-examples but it should be working and it shows a minimal example.

2024-03-20 08:51 UTC, ilgrosso commented
Thank you @silasporth I was able to get around it: https://github.com/apache/syncope/commit/f00ad780eab55ea9cfcf6caf9c5a822a73a76a41