#926 Use Webjars for JQueryUI
wicketstuff/core pull request #927
Opened 2024-06-06 08:03 UTC by mcr-paulanand

Resolves #926

2024-06-06 08:08 UTC, solomax requested changes
I would also 

 - use `*.css` from webjars for this `base` theme wicket-jquery-ui-parent/wicket-jquery-ui-themes/theme-base/src/main/java/com/googlecode/wicket/jquery/ui/theme/Initializer.java
 - `WicketWebjars.install(this);` should be added to `wicket-jquery-ui-parent/wicket-jquery-ui-samples/src/main/java/com/googlecode/wicket/jquery/ui/samples/SampleApplication.java`, otherwise examples will not work ....

2024-06-06 08:08 UTC, solomax commented on wicketstuff-jquery-ui-parent/wicketstuff-jquery-ui/src/main/java/org/wicketstuff/jquery/ui/resource/JQueryUIResourceReference.java
> +		super("jquery-ui/current/jquery-ui.min.js");
I believe `.min` should be removed here ...

2024-06-06 08:30 UTC, solomax commented on wicketstuff-jquery-ui-parent/wicketstuff-jquery-ui-themes/wicketstuff-jquery-ui-theme-base/src/main/java/org/wicketstuff/jquery/ui/theme/Initializer.java
> +		JQueryUILibrarySettings.get().setStyleSheetReference(new WebjarsCssResourceReference("jquery-ui/current/jquery-ui.css"));
@mcr-paulanand correspondent `*.css` files need to be removed from sources :)

2024-06-06 08:32 UTC, solomax approved these changes

2024-06-06 14:15 UTC, merged

2024-06-06 16:41 UTC, solomax commented
Hello @martin-g,

It seems this PR breaks samples

Webjars are being used from `Initializer` from now on

so we got 
```
Caused by: java.lang.IllegalStateException: you have to call WicketWebjars.install() before you can use an IWebjarsResourceReference or any other component.
    at de.agilecoders.wicket.webjars.WicketWebjars.settings (WicketWebjars.java:136)
    at de.agilecoders.wicket.webjars.util.WebjarsVersion$Holder.<clinit> (WebjarsVersion.java:29)
    at de.agilecoders.wicket.webjars.util.WebjarsVersion.useRecent (WebjarsVersion.java:45)
    at de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference.<init> (WebjarsJavaScriptResourceReference.java:29)
    at org.wicketstuff.jquery.ui.resource.JQueryUIResourceReference.<init> (JQueryUIResourceReference.java:54)
    at org.wicketstuff.jquery.ui.resource.JQueryUIResourceReference.<clinit> (JQueryUIResourceReference.java:37)
    at org.wicketstuff.jquery.ui.settings.JQueryUILibrarySettings.<init> (JQueryUILibrarySettings.java:49)
    at org.wicketstuff.jquery.ui.settings.JQueryUILibrarySettings.get (JQueryUILibrarySettings.java:61)
    at org.wicketstuff.jquery.ui.theme.Initializer.init (Initializer.java:37)
    at org.apache.wicket.Application.initInitializers (Application.java:561)
    at org.apache.wicket.Application.initApplication (Application.java:767)
    at org.apache.wicket.protocol.http.WicketFilter.init (WicketFilter.java:441)
```

due to `WicketWebjars.install(this);` is being called in the `init()` i.e. too late :(

What can be done here?

2024-06-06 19:04 UTC, martin-g commented
As error message suggests we need to add 'WicketWebjars.install()' to the respective WebApplication#init()

2024-06-06 19:06 UTC, martin-g commented
Oh, now I see the text after the stacktrace. 
I think it should be OK to call it in an initializer too.

2024-06-07 01:59 UTC, solomax commented
Works as expected!

Thanks a million @martin-g :)

2024-06-07 08:24 UTC, reckart commented
> due to WicketWebjars.install(this); is being called in the init() i.e. too late :(

@solomax so how did you solve this?

2024-06-07 08:26 UTC, solomax commented
> @solomax so how did you solve this?

https://github.com/wicketstuff/core/blob/master/wicketstuff-jquery-ui-parent/wicketstuff-jquery-ui-themes/wicketstuff-jquery-ui-theme-base/src/main/java/org/wicketstuff/jquery/ui/theme/Initializer.java#L36

:))

2024-06-07 08:30 UTC, reckart commented
I think this change needs to be made in the initializer of **all** of the themes separately.

2024-06-07 08:44 UTC, solomax commented
> I think this change needs to be made in the initializer of **all** of the themes separately.

I also thought so

But I believe right now it's not necessary due to the fact the only theme uses webjar so far :)

2024-06-07 09:20 UTC, mcr-paulanand commented
> > I think this change needs to be made in the initializer of **all** of the themes separately.
> 
> I also thought so
> 
> But I believe right now it's not necessary due to the fact the only theme uses webjar so far :)

I have created a PR #934 to resolve this